import Head from 'next/head'
import Header from '../components/Header'
import NavBar from '../components/NavBar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src="https://cdn.lordicon.com/xdjxvujz.js"></script>


      {/* HEADER*/}
      <Header/>

      {/*NavBar*/}
      <NavBar />

    </div>
  )
}
